# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4328e850ac36cbd7646aa38926ca197241415e6ba3f5404f72aeba7550f3b64452ee0f5af3672feb6120ca7e32c4681452a733a5ad3987ceba978e38a14ecc19

test:
  secret_key_base: 44d7859d7f465400c52c63de20ce7a2600ed128bf7a898ac2e267ae78f005629b63cd297788e5ebd2ba97a85333938c0fa31e63ae0d9f17f5468bd76ac360d87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
